version: '3.8'
services:
  app:
    volumes:
      - ..:/workspaces:cached
    command: sleep infinity

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: user_pg
      POSTGRES_PASSWORD: password_pg
      POSTGRES_DB: database_pg
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres_secondary:
    image: postgres:latest
    container_name: postgres_secondary
    environment:
      POSTGRES_USER: user_pg_secondary
      POSTGRES_PASSWORD: password_pg_secondary
      POSTGRES_DB: database_pg_secondary
    ports:
      - "5433:5432"
    volumes:
      - postgres_secondary_data:/var/lib/postgresql/data

  postgres_tertiary:
    image: postgres:latest
    container_name: postgres_tertiary
    environment:
      POSTGRES_USER: user_pg_tertiary
      POSTGRES_PASSWORD: password_pg_tertiary
      POSTGRES_DB: database_pg_tertiary
    ports:
      - "5434:5432"
    volumes:
      - postgres_tertiary_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  postgres_secondary_data:
  postgres_tertiary_data:
